In [1]:
import numpy as np

### data load

data : [  
&nbsp;&nbsp;&nbsp;&nbsp;[ user_id, ?, rating, ? ],  
&nbsp;&nbsp;&nbsp;&nbsp;...   
]

In [3]:
data = np.loadtxt("data/movielens/ratings.dat", \
                  delimiter = "::", dtype = np.int64)

In [10]:
data[:5, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [5]:
data.shape

(1000209, 4)

### 전체 평균

In [6]:
## index 2 : 평점
total_mean = data[:, 2].mean()
total_mean

3.581564453029317

### user id data

In [7]:
user_ids = np.unique(data[:, 0])

In [9]:
user_ids[:5], user_ids.shape

(array([1, 2, 3, 4, 5], dtype=int64), (6040,))

### mean rating by each unique user

In [11]:
mean_rating_by_user_list = []
for user_id in user_ids:
    data_for_user = data[ data[:, 0] == user_id, :]
    mean_rating_for_user = data_for_user[:, 2].mean()
    mean_rating_by_user_list.append( [user_id, mean_rating_for_user] )

In [12]:
mean_rating_by_user = np.array(mean_rating_by_user_list)

In [14]:
mean_rating_by_user[:5], mean_rating_by_user.shape

(array([[1.        , 4.18867925],
        [2.        , 3.71317829],
        [3.        , 3.90196078],
        [4.        , 4.19047619],
        [5.        , 3.14646465]]),
 (6040, 2))

### save as file

In [15]:
np.savetxt("mean_rating_by_user.csv",\
           mean_rating_by_user, fmt="%.3f", delimiter=',')